

name: Java CI with Gradle

on:

  pull_request:


permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Create secret.yml
      env:
        SECRET_CODE: ${{ secrets.SECRET }}
        SECRET_DIR: src/main/resources
        SECRET_FILE_NAME: secret.yml
      run: echo $SECRET_CODE | base64 --decode > $SECRET_DIR/$SECRET_FILE_NAME


    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name : Set Eureka Server
      run: |
        docker pull ${{ secrets.EUREKA  }}
        docker run -d -p 8761:8761 $${{ secrets.EUREKA }}

    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
